services:
  - type: web
    name: fishers-guidapp-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://fishingapp-u4z6.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
